name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - name: Install frontend dependencies
        run: bun install --frozen-lockfile --verbose
        working-directory: streamlit_shadcn_ui/components/packages/frontend
      - name: Build frontend
        run: bun run build
        working-directory: streamlit_shadcn_ui/components/packages/frontend
      - name: Install uv 
        uses: astral-sh/setup-uv@v5
      - name: Build Python package with UV
        run: uv build
      - name: Commit and Push Changes
        uses: devops-infra/action-commit-push@v0.10.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "chore: commit build artifacts"
          force: true
          file_pattern: |
            streamlit_shadcn_ui/components/packages/frontend/dist
            dist